Repository NaKaLiGoBa/AlgoWithMe-FE, pull requests merged in 2023-10, with the labels that each got.

#13 Design: 알고리즘 문제 페이지 UI 추가
  src/components/UI/molecules/Problems/constant.js
  src/components/UI/molecules/Problems/index.jsx
  src/components/pages/IDEPage/index.jsx
Labels: 💜 FE, 🎨 design

#14 7 전체 알고리즘 문제 리스트 보기
  src/components/UI/atoms/Text/Link/index.js
  src/components/UI/atoms/Text/Link/index.jsx
  src/components/UI/atoms/Text/Text/index.js
  src/components/UI/atoms/Text/Text/index.jsx
  src/components/UI/molecules/Navigation/Footer/index.jsx
  src/components/UI/molecules/Navigation/Navbar/index.js
  src/components/UI/molecules/Navigation/Navbar/index.jsx
  src/components/UI/molecules/Problem/ProblemItem/index.jsx
  src/components/UI/molecules/Problem/ProblemList/index.jsx
  src/components/UI/molecules/Problem/ProblemListHeader/index.jsx
  src/components/pages/HomePage/index.jsx
Labels: 💜 FE, 🎨 design

#16 Design: Auth 페이지 UI 추가
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.jsx
  src/components/UI/atoms/Input/Button/index.jsx
  src/components/UI/atoms/Input/Input/index.jsx
  src/components/UI/atoms/Input/Textarea/index.js
  src/components/UI/atoms/Input/Textarea/index.jsx
  src/components/UI/atoms/Text/Heading/index.js
  src/components/UI/atoms/Text/Heading/index.jsx
  src/components/UI/atoms/Text/Text/index.jsx
  src/components/UI/molecules/Feedback/Alert/index.js
  src/components/UI/molecules/Feedback/Alert/index.jsx
  src/components/UI/molecules/Form/Signin/index.js
  src/components/UI/molecules/Form/Signin/index.jsx
  src/components/UI/molecules/Form/Signup/index.js
  src/components/UI/molecules/Form/Signup/index.jsx
  src/components/pages/AuthPage/SigninPage/index.jsx
  src/components/pages/AuthPage/SignupPage/index.jsx
  src/components/pages/AuthPage/index.jsx
  src/main.jsx
Labels: 💜 FE, 🎨 design

#23 7 전체 알고리즘 문제 리스트 보기
  package-lock.json
  public/api/v1/TestProblemData.json
  src/components/UI/atoms/Text/Link/index.jsx
  src/components/UI/atoms/Text/Text/index.jsx
  src/components/UI/molecules/Navigation/Footer/index.jsx
  src/components/UI/molecules/Navigation/Header/index.jsx
  src/components/UI/molecules/Navigation/Navbar/index.jsx
  src/components/UI/molecules/Problem/ProblemItem/index.jsx
  src/components/UI/molecules/Problem/ProblemList/index.jsx
  src/components/UI/molecules/Problem/ProblemListFooter/index.jsx
  src/components/UI/molecules/Problem/ProblemListHeader/index.jsx
  src/components/pages/HomePage/index.jsx
  src/hooks/usePaginationRange.jsx
Labels: 💜 FE, 🎨 design, 🌟 feat

#22 feat: 로그인 페이지 - 카카오 아이디로 회원가입 및 로그인
  .gitignore
  package-lock.json
  package.json
  public/assets/img/kakao.png
  src/App.jsx
  src/components/UI/atoms/Input/Button/index.jsx
  src/components/UI/molecules/Feedback/Alert/index.jsx
  src/components/UI/molecules/Form/Signin/index.jsx
  src/components/UI/molecules/Form/Signup/index.jsx
  src/components/pages/AuthPage/kakaologin/index.jsx
Labels: 💜 FE, 🌟 feat

#20 feat: 12 코드 제출 후 정답 여부 확인
  package-lock.json
  src/components/UI/atoms/Input/Button/index.jsx
  src/components/UI/molecules/Editor/index.jsx
  src/components/UI/molecules/OutputPanel/index.jsx
  src/components/UI/molecules/ProblemPanel/index.jsx
  src/components/UI/templates/IDETemplate.jsx
  src/components/pages/IDEPage/constant.jsx
  src/components/pages/IDEPage/index.jsx
  src/utils/apiConfig.js
  src/utils/problemApi.js
  src/utils/runTestCodeApi.js
  src/utils/submitCodeApi.js
Labels: 💜 FE, 🎨 design, 🌟 feat

#18 chore: 프론트엔드 도커파일 추가
  Dockerfile
Labels: 🧱 devops

#30 전체 알고리즘 문제 리스트 보기
  .env
  db.json
  public/api/TestProblemData.json
  src/components/UI/molecules/Problem/ProblemList/index.jsx
  src/components/UI/templates/IDETemplate.jsx
  src/config/api-config.js
  src/service/api.jsx
  src/service/problemListService.jsx
Labels: 💜 FE
