Repository NaKaLiGoBa/AlgoWithMe-FE, pull requests merged in 2023-11, with the labels that each got.

#26 회원가입 별 상태코드 부여
  src/App.jsx
  src/components/UI/molecules/Form/Signin/index.jsx
  src/components/UI/molecules/Form/Signup/index.jsx
  src/components/UI/molecules/Navigation/Header/index.jsx
  src/components/pages/AuthPage/PasswordEmail/index.jsx
  src/components/pages/AuthPage/PasswordReset/index.jsx
  src/components/pages/AuthPage/kakaologin/index.jsx
  src/utils/apiConfig.js
Labels: 💜 FE, 🌟 feat

#32 풀이 글 리스트 보기
  package-lock.json
  package.json
  public/api/page1.json
  public/api/page2.json
  public/api/page3.json
  src/components/UI/atoms/Tab/styles.css
  src/components/UI/molecules/ListItem/index.jsx
  src/components/UI/molecules/ProblemTab/index.jsx
  src/components/UI/molecules/Solutions/index.jsx
  src/service/SolutionsService.jsx
  src/store/SolutionsSlice.jsx
  src/store/index.jsx
  src/store/tabState.jsx
Labels: 💜 FE, 🎨 design, 🌟 feat

#34 [feat] 풀이 글 작성
  package-lock.json
  package.json
  src/App.jsx
  src/components/UI/molecules/MdEditor/index.jsx
  src/components/UI/molecules/Navigation/Header/index.jsx
  src/components/UI/templates/SolutionEditTemplate/contentTemplate.js
  src/components/UI/templates/SolutionEditTemplate/index.jsx
  src/components/pages/SolutionEditPage/index.jsx
Labels: 💜 FE, 📦 chore, 🎨 design, 🌟 feat

#33 풀이 글 보기
  package-lock.json
  package.json
  src/components/UI/molecules/ProblemTab/index.jsx
  src/components/UI/molecules/SolutionTest/index.jsx
  src/store/tabState.jsx
  src/utils/fetchSolution.js
Labels: 💜 FE, 🎨 design, 🌟 feat

#42 [feat] 문제 디테일 글에 댓글 기능 추가
  src/App.jsx
  src/components/UI/atoms/Input/Comment/index.jsx
  src/components/UI/atoms/Input/CommentInput/index.jsx
  src/components/UI/atoms/Input/LikeButton/index.jsx
  src/components/UI/atoms/Input/ReplyButton/index.jsx
  src/components/UI/atoms/Toggle/RepliesToggleButton/index.jsx
  src/components/UI/molecules/CommentSection/index.jsx
  src/components/UI/molecules/CommentsSection/index.jsx
  src/components/UI/molecules/SolutionTest/index.jsx
  src/utils/api/v1/comment/postCommentBySolutionId.js
Labels: 💜 FE, 🎨 design, 🌟 feat

#41 37 미니퀴즈 보기
  public/api/miniQuiz.json
  src/App.jsx
  src/components/UI/atoms/Icon/Close/index.jsx
  src/components/UI/atoms/Icon/Plus/index.jsx
  src/components/UI/atoms/Icon/TrueOrFalse/index.jsx
  src/components/UI/atoms/Icon/TrueOrFalse/styles.css
  src/components/UI/atoms/Input/Checkbox/index.js
  src/components/UI/atoms/Input/Radio/index.js
  src/components/UI/atoms/Input/Radio/index.jsx
  src/components/UI/molecules/ProblemPanel/index.jsx
  src/components/UI/molecules/Quiz/AnswerExplanation/index.jsx
  src/components/UI/molecules/Quiz/Initials/index.jsx
  src/components/UI/molecules/Quiz/MultipleChoice/index.jsx
  src/components/UI/molecules/Quiz/QuestionBox/index.jsx
  src/components/UI/molecules/Quiz/QuizNavigaionButton/index.jsx
  src/components/UI/molecules/Quiz/TrueOrFalse/index.jsx
  src/components/UI/templates/ProblemQuizzesTemplate/index.jsx
  src/components/pages/ProblemQuizzesPage/index.jsx
  src/store/index.jsx
  src/store/quizSlice.jsx
  src/utils/api/v1/problem/getQuizzesByProblemId.jsx
  src/utils/apiConfig.js
Labels: 💜 FE, 🎨 design, 🌟 feat

#40 [feat] 문제 리스트에 sort 기능
  public/assets/img/logo_awm_dark.png
  public/assets/img/logo_awm_light.png
  src/App.jsx
  src/components/UI/atoms/Avatar/index.jsx
  src/components/UI/atoms/Input/Dropdown/index.jsx
  src/components/UI/atoms/Logo/index.jsx
  src/components/UI/atoms/Media/Image/index.js
  src/components/UI/atoms/Media/Image/index.jsx
  src/components/UI/molecules/ListItem/index.jsx
  src/components/UI/molecules/Navigation/Header/index.jsx
  src/components/UI/molecules/Problem/ProblemList/index.jsx
  src/components/UI/molecules/Solutions/index.jsx
  src/components/UI/templates/HomeTemplate/index.jsx
  src/components/pages/HomePage/index.jsx
  src/utils/api/v1/problem/getProblems.jsx
Labels: 💜 FE, 🎨 design, 🌟 feat, 📐 refactor

#49 [feat] 45 솔루션 api 연동
  src/App.jsx
  src/components/UI/molecules/Editor/index.jsx
  src/components/UI/molecules/Form/Signin/index.jsx
  src/components/UI/molecules/MdEditor/index.jsx
  src/components/UI/molecules/Navigation/Header/index.jsx
  src/components/UI/molecules/OutputPanel/index.jsx
  src/components/UI/molecules/ProblemPanel/index.jsx
  src/components/UI/molecules/Solutions/index.jsx
  src/components/UI/templates/IDETemplate/index.jsx
  src/components/UI/templates/SolutionEditTemplate/index.jsx
  src/components/pages/IDEPage/index.jsx
  src/service/AuthLayer.jsx
  src/service/problemListService.jsx
  src/store/problemSlice.jsx
  src/utils/api.js
  src/utils/api/v1/solution/getSolutions.js
  src/utils/api/v1/solution/postSolutionByProblemId.js
  src/utils/apiConfig.js
  src/utils/problemApi.js
  src/utils/runTestCodeApi.js
  vite.config.js
Labels: 💜 FE, 📦 chore, 🎨 design, 🌟 feat
